[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5.0-alpha.0", features = ["desktop"] }
itertools = "0.12.1"

[[bin]]
name = "ara"
path = "src/main.rs"

[build-dependencies]
glib-build-tools = "0.19.0"
